apiVersion: apps/v1
kind: Deployment
metadata:
  name: professional-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: professional-website
  template:
    metadata:
      labels:
        app: professional-website
    spec:
      containers:
        - name: website
          image: saxenad592/professional-website:latest
          ports:
            - containerPort: 80

